### ISSUE TITLE
[Feature Request] RTL Language Support

### ISSUE THREAD

**Issue by SepSol** [Jisco/VisualFamilyTree#1]
Hi, thanks for your amazing unique app! Can you please add better right-to-left language support and better fonts for Arabic/Persian languages? I could help you pick a font and even add a translation for Persian users.

**Comment by Jisco** [comment]
Hi,
I have to admit to my shame that I didn't even think about it. 😅 
But luckily that shouldn't be a great problem! 💪 

It would be great if you could suggest some fonts to me and I could also send you the translation file, that would be really awesome if you add an translation.

Then i'll try to add RTL support in one of the next updates.

**Comment by SepSol** [comment]
I'm glad that you're considering this 😁

Ok, so I've looked up some open-source Persian fonts and I think I've found the one that goes well with the aesthetics and design of the English version of your app. Here's [its GitHub page](http://rastikerdar.github.io/gandom-font/), and here's [its GitHub repo](https://github.com/rastikerdar/gandom-font). This font is kind of equivalent to the stylish serif English font you've used but in Persian script.

![image](https://user-images.githubusercontent.com/47871887/85921610-96070580-b892-11ea-98fb-8b9471cc0298.png)

I'm ready for the translation file 😋

**Comment by Jisco** [comment]
Sure,
i have uploaded the actual translation files and a short [readme](https://github.com/Jisco/VisualFamilyTree/blob/master/Languages/ReadMe.md).

Is this ok?

The font really looks very appropriate. I'll give it a try :running:

Thanks for your effort! :clap::clap::clap:

**Comment by SepSol** [comment]
No problem dude, I think this is all well and good. Just give me a few days and I'll finish the translation 💪🏻

**Comment by Jisco** [comment]
#

**Comment by Jisco** [comment]
#2

**Comment by Jisco** [comment]
I try to test it on the weekend...

**Comment by SepSol** [comment]
Thanks, mate. I'm available. Hit me up if there was anything I could do 😉

**Comment by Jisco** [comment]
@SepSol 

Unfortunately (or logically) there is no icon for the ISO code 'fa'. 😟 
Now I don't know what to show in the language selection...

 Any idea? Is there any universal sign for this?

**Comment by SepSol** [comment]
Yeah, the country name and language name are a little bit different. Here's how to handle it:

* inside [](http://www.mathguide.de/info/tools/languagecode.html):
![image](https://user-images.githubusercontent.com/47871887/86483593-9f4c1280-bd69-11ea-9dcc-bb2bba07bdfa.png)

* inside [](https://github.com/lipis/flag-icon-css/tree/master/flags/4x3):
![image](https://user-images.githubusercontent.com/47871887/86483794-0a95e480-bd6a-11ea-81bd-91a06a0d1890.png)

**Comment by Jisco** [comment]
Hi,
Yes, thank you.

I made the language file selectable and switched the component library to RTL.

2 "Little things" are unfortunately not working (yet) because the library ([DevExtreme ](https://js.devexpress.com/) by the way) does not fully support Persian. Some things are still not translated there and the Persian date format is unfortunately not supported either. That is why the English format is still set there.

If you tell me whether you are a Windows or Linux user, I will post a version here so that you can see for yourself what is ok and what I could possibly improve!

Thanks anyway for your efforts!

**Comment by SepSol** [comment]
Wow! That looks awesome 😋
I was going to ask for the Persian calendar integration, thanks for keeping an eye out!
Sure thing, I'm on Windows. 🙌🏻

**Comment by Jisco** [comment]
In order to alleviate the problem with the calendar a little, I made 2 preview versions. One in which the entire English format is used and one where the input is in English format but the display is in Persian format.

Here is the download link: [https://we.tl/t-WHSkQujFvF](https://we.tl/t-WHSkQujFvF)
I then wait for your suggestions 😀

**Comment by SepSol** [comment]
@Jisco 
I appreciate your efforts in trying to make a Persian translation of the dates available to Persian users. Honestly, which version I choose comes down to personal preference. I would go with the Persian version myself, but either is good.

Now having my hands on this version, there are some things that I've noticed. Some I should fix in the translation file and make another pull request for you, some I should ask you.

One is this:
![image](https://user-images.githubusercontent.com/47871887/86533271-3e494980-bee5-11ea-800d-7ca24c989b69.png)
If you look at the Persian text on the left and compare it with the one on the right, you'll notice that there's one dot/point missing from the text on the left (the text should read سپهر, which has 3 dots under it). I think this could be because of more tight line-spacing on the card which is on the left-hand side. So I would suggest increasing the line-spacing on the cards for better readability.

Two is this:
![image](https://user-images.githubusercontent.com/47871887/86533356-d8a98d00-bee5-11ea-9f7c-8420cf0011d0.png)
The card on the left is from the English version of the app with some Persian text on it, and the right card is from the Persian version of the app with some English and Persian text on it. Basically what I wanted to point out is that the English font applies to the Persian version, but the Persian font didn't apply to the English version. If this went both ways it would be nice!

But other than these it is looking better than I thought in Persian 😋. I still have to make some corrections and make a new pull request soon though.

**Comment by SepSol** [comment]
I made a new pull request. I noticed some other things that I wish could be polished.

1. It would be great if I could translate these texts:
![image](https://user-images.githubusercontent.com/47871887/86558017-595f9c00-bf6d-11ea-8c59-18d8badb3347.png)
![image](https://user-images.githubusercontent.com/47871887/86558047-798f5b00-bf6d-11ea-91a1-ffdc3f922b9f.png)

2. I would suggest an exact copy of the English layout for these two "Help" pages (title bar could become left-aligned):
![image](https://user-images.githubusercontent.com/47871887/86558223-0a663680-bf6e-11ea-86b8-c81357475331.png)
![image](https://user-images.githubusercontent.com/47871887/86558239-13570800-bf6e-11ea-8dcd-e54a82d7bd55.png)

3. I would suggest changing the layout of the home screen for RTL languages from this:
![image](https://user-images.githubusercontent.com/47871887/86558292-37b2e480-bf6e-11ea-8986-f9a29d60bf27.png)
to this:
![image](https://user-images.githubusercontent.com/47871887/86560344-4e0f6f00-bf73-11ea-94f4-90f94b3b97c4.png)

I hope I'm not asking for too much 🙊

**Comment by Jisco** [comment]
No problem. 👍  I also asked you about your suggestions. 😀 

So I looked at your comments and decided to make the whole thing adjustable.

* Separate language setting and font
  * for example English as language but Gandom as font
* Own line spacing settings
  * because it depends on the choosen font

I will also search the entire app to see if the correct font is used everywhere.

The "drop here...", "No data" and "Search..." texts come directly from the component framework. In english or german they are automatically translated, but because they don't have a persian translation they show english as standard.
But we can make the translation by ourselfs. So i will search the keys and add these to the translation file! 🚀

**Comment by Jisco** [comment]
I will update these list to show progress.

TODO List:
- [ ] Separate language and font settings
- [ ] Adjustable line spacing
- [ ] Research font settings everywhere
- [ ] Add translation for components
- [ ] Change home screen to rtl

**Comment by SepSol** [comment]
> No problem. 👍 I also asked you about your suggestions. 😀
> 
> So I looked at your comments and decided to make the whole thing adjustable.
> 
> * Separate language setting and font
>   
>   * for example English as language but Gandom as font
> * Own line spacing settings
>   
>   * because it depends on the choosen font
> 
> I will also search the entire app to see if the correct font is used everywhere.
> 
> The "drop here...", "No data" and "Search..." texts come directly from the component framework. In english or german they are automatically translated, but because they don't have a persian translation they show english as standard.
> But we can make the translation by ourselfs. So i will search the keys and add these to the translation file! 🚀

Thank you sooo much 😍😊

**Comment by Jisco** [comment]
@SepSol:

I have added all translation keys that i found in the components to the [fa.js](https://github.com/Jisco/VisualFamilyTree/blob/master/Languages/fa.js) file..
So these file is ready to be translated. 🚀

**Comment by SepSol** [comment]
Awesome! I created [another pull request](https://github.com/Jisco/VisualFamilyTree/pull/4). 🙊

**Comment by Jisco** [comment]
Hi @SepSol,
So I have now made all changes (at least I hope 😁) and uploaded a new preview version for testing.  [Click here...](https://nc.jisco.me/index.php/s/J8ToDtyXT5QDt7T)

I also added the Spanish translation, so it would be great if @MrOlivo will also checking if it all fits.

For the new functions I have added more translations and used Google Translator (shame on me 😅). So it would be very nice if you would tell me if that would fit. If not please create a new pull request for it. 👍 

I will be looking forward to your feedback 🚀
Thanks again for your contributions 🥰

**Comment by SepSol** [comment]
@Jisco you are awesome! Everything is well and great! I only noticed these checkboxes not aligning themselves properly in the Farsi/Persian version:
![image](https://user-images.githubusercontent.com/47871887/87856688-e8898e00-c935-11ea-838e-94f013c6c40e.png)
Take a look at this mockup from earlier for reference:
![image](https://user-images.githubusercontent.com/47871887/87856697-fccd8b00-c935-11ea-801a-d061c31a3c4b.png)

**Comment by Jisco** [comment]
@SepSol
I think i can fix this before releasing the new version 😀 😜

**Comment by MrOlivo** [comment]
@Jisco 
Everything seems to be in order, I just have to correct the spelling mistakes and a few meaningless phrases.
I've never used the dictionary 📖  so much before 😅

**Comment by Jisco** [comment]
@MrOlivo 
Thank you very much. 😄
