### ISSUE TITLE
Allow import of families in GEDCOM

### ISSUE THREAD

**Issue by jacebenson** [Jisco/VisualFamilyTree#11]
https://en.wikipedia.org/wiki/GEDCOM

I'm not sure what this would take.  Looks like there's [code to do this already](https://github.com/tmcw/parse-gedcom) but it will likely have to match your format

**Comment by Jisco** [comment]
Yes!
Importing (and possibly exporting) into the GEDCOM format is one of the next items on my TODO list. 👍

**Comment by Jisco** [comment]
🎉 Good News... if tested import from different gedcom files ("only" names and relationsships) and it works very good.
Just have to add more data like dates and events.

**Comment by Jisco** [comment]
BTW, i wrote my own gedcom <-> json converter... :sweat_smile:

[Github](https://github.com/Jisco/gedcom.json)
[NPM](https://www.npmjs.com/package/gedcom.json)

**Comment by Jisco** [comment]
Closed with Version 1.4.0
