### ISSUE TITLE
Cannot run on Windows 32 Bit System

### ISSUE THREAD

**Issue by nileshbandhiya** [Jisco/VisualFamilyTree#20]
I wish to run the software for on my system 32 bit Windows 7. But it is not allowed to run.

**Comment by Jisco** [comment]
Hi,
i will try to build an 32bit Version on the weekend and notify you when it is available.

**Comment by nileshbandhiya** [comment]
Thanks.

I am waiting for the version.

Regards,
Nilesh Bandhiya

     On Wednesday, 15 June, 2022, 12:38:31 pm IST, Jens ***@***.***> wrote:  
 
 


Hi,
i will try to build an 32bit Version on the weekend and notify you if it is available.

**Comment by Jisco** [comment]
@nileshbandhiya 
hi,
please try this executable: https://github.com/Jisco/VisualFamilyTree/releases/download/v1.4.0/VisualFamilyTree.1.4.0.portable-ia32.exe

hope it works 😁

**Comment by nileshbandhiya** [comment]
Thanks. It works.

How can I remove default picture?

**Comment by Jisco** [comment]
What do you mean with the "default picture" ?

**Comment by nileshbandhiya** [comment]
Regards,
Nilesh Bandhiya

Defailt Icon for Man or Woman. I need just plain name without picture. And I am not able to load a gedcom file attached here.     On Monday, 20 June, 2022, 07:35:17 pm IST, Jens ***@***.***> wrote:  
 
 


What do you mean with the "default picture" ?

**Comment by Jisco** [comment]
There is (actually) no way to remove the picture in the chart view. Can you attach the gedcom file here or send it via jisco@jisco.me? Then i will have a look.

**Comment by nileshbandhiya** [comment]
Regards,
Nilesh Bandhiya
     On Thursday, 23 June, 2022, 10:09:41 am IST, Jens ***@***.***> wrote:  
 
 


There is (actually) no way to remove the picture in the chart view. Can you attach the gedcom file here or send it via ***@***.***? Then i will have a look.

**Comment by Jisco** [comment]
When you answer to this as an email i dont get the attachment. Please attach the file here (on github) or send it to jisco@jisco.me
