### ISSUE TITLE
[Feature Request] Open directory with exported image.

### ISSUE THREAD

**Issue by Gimanh** [Jisco/VisualFamilyTree#9]
I think will be good fo UX if app will automatically open directory with exported dataset/image.

**Comment by Jisco** [comment]
Do you mean when importing\exporting records?

**Comment by Gimanh** [comment]
> Do you mean when importing\exporting records?

Yes.

**Comment by Jisco** [comment]
Ahh, ok... should be no problem. Thank you for the hint. 👍

**Comment by Jisco** [comment]
Implemented with <a href="https://github.com/Jisco/VisualFamilyTree/blob/master/v1.3.1.md">Version 1.3.1</a>
